# Cloud Build Configuration for .circleci base image build:
# - Builds and pushes gcr.io/tpu-pytorch/xla_base:{_TAG_NAME}.
# - This build is meant to be triggered manually in cloud builder
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build',
          '--build-arg', 'cloud_build_prefix=.cicleci/docker',
          '--build-arg', 'base_image=${_BASE_IMAGE}',
          '--build-arg', 'cuda=${_CUDA}',
          '--build-arg', 'python_version=${_PYTHON_VERSION}',
          '-t', 'gcr.io/tpu-pytorch/xla_base:${_TAG_NAME}',
          '-f', '.circleci/docker/Dockerfile', '.circleci/docker/'
        ]
  timeout: 2000s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/tpu-pytorch/xla_base']
  timeout: 1000s

options:
    machineType: 'N1_HIGHCPU_32'
    dynamic_substitutions: true
    substitution_option: 'ALLOW_LOOSE'
substitutions:
    _CUDA: '1'
    _BASE_IMAGE: 'us-central1-docker.pkg.dev/tpu-pytorch-releases/docker/development:3.10_cuda_12.3'
    _PYTHON_VERSION: '3.10'
    _TAG_NAME: '${_PYTHON_VERSION}-mini'
timeout: 3000s
